"""Increase picture column length to 512

Revision ID: 7008a4fbb3b2
Revises: 4f65ca61a113
Create Date: 2025-02-11 01:12:11.822447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7008a4fbb3b2'
down_revision = '4f65ca61a113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###
