"""Bring DB to the current code

Revision ID: bc28869d5158
Revises: 941585d14839
Create Date: 2025-01-26 23:56:05.549398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc28869d5158'
down_revision = '941585d14839'
branch_labels = None
depends_on = None


def upgrade():
    # Add the column with a default value for existing rows
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('completed_at', sa.DateTime(), nullable=False, server_default=sa.func.now())
        )
    # Remove the server default after setting it
    op.execute("ALTER TABLE user_activity ALTER COLUMN completed_at DROP DEFAULT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
